name: continuous integration

on:
  pull_request:
    branches: [main]

jobs:
  test_pull_request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build CSS/Tailwind
        run: npx tailwindcss build -o dist.css  # Process Tailwind first if needed

      - name: Run tests
        run: npm test -- --watch=false --browsers=ChromeHeadless  # Run tests in headless mode

      - name: Build project
        run: npm run build -- --configuration=production